site_name: Vapor 4 速成指南
site_description: 'Vapor 4 速成指南'
site_author: 'Cary Zheng'
site_url: 'https://vapor4.swiftmic.com'
copyright: 'Copyright &copy; 2019 CaryZheng'
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  favicon: 'favicon.ico'
  logo: 'logo.png'
google_analytics:
  - 'UA-113865151-2'
  - 'auto'
nav:
- 序: index.md
- 安装 Vapor:
  - macOS: install/install_mac.md
  - Linux: install/install_linux.md
- Hello World: hello_world.md
- Toolbox: toolbox.md
- 基础组件:
  - Application: base/application.md
  - Controller: base/controller.md
  - Routing: base/routing.md
  - Provider: base/provider.md
  - Middleware: base/middleware.md
- 数据库:
  - MySQL: database/mysql.md
  - Redis: database/redis.md
- 测试: test.md
- 部署: deploy.md