site_name: Vapor 4 速成指南
site_description: 'Vapor 4 速成指南'
site_author: 'Cary Zheng'
site_url: 'https://vapor4.swiftmic.com'

repo_name: 'CaryZheng/Vapor4-Tutorial'
repo_url: 'https://github.com/CaryZheng/Vapor4-Tutorial'

copyright: 'Copyright &copy; 2022 CaryZheng'

theme:
  name: 'material'
  palette:
    # - media: "(prefers-color-scheme: light)"
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: zh
  favicon: favicon.ico
  logo: logo.png

extra:
  analytics:
    provider: google
    property: UA-113865151-2
  social:
    - icon: fontawesome/brands/medium
      link: https://www.carymic.com
    - icon: fontawesome/brands/github
      link: https://github.com/CaryZheng


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
- 序: index.md
- 开发环境: install_vapor.md
- Hello World: hello_world.md
- SPM: spm.md
- 基础组件:
  - Application: base/application.md
  - Controller: base/controller.md
  - Routing: base/routing.md
  - Middleware: base/middleware.md
- 数据库:
  - MySQL: database/mysql.md
  - Redis: database/redis.md
- 多环境配置: environment.md
- 日志: logger.md
- 测试: test.md
- 部署: deploy.md