site_name: Vapor 4 速成指南
site_description: 'Vapor 4 速成指南'
site_author: 'Cary Zheng'
site_url: 'https://vapor4.swiftmic.com'

repo_name: 'CaryZheng/Vapor4-Tutorial'
repo_url: 'https://github.com/CaryZheng/Vapor4-Tutorial'

copyright: 'Copyright &copy; 2019 CaryZheng'

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  favicon: 'favicon.ico'
  logo: 'logo.png'

google_analytics:
  - 'UA-113865151-2'
  - 'auto'

extra:
  social:
    - type: globe
      link: https://www.carymic.com
    - type: github-alt
      link: https://github.com/CaryZheng

markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
- 序: index.md
- 开发环境: install_vapor.md
- Hello World: hello_world.md
- SPM: spm.md
- 基础组件:
  - Application: base/application.md
  - Controller: base/controller.md
  - Routing: base/routing.md
  - Middleware: base/middleware.md
- 数据库:
  - MySQL: database/mysql.md
  - Redis: database/redis.md
- 多环境配置: environment.md
- 测试: test.md
- 部署: deploy.md